export enum ContentType {
  JSON = "application/json",
  FORM_URLENCODED = "application/x-www-form-urlencoded",
  FORM_DATA = "multipart/form-data",
  TEXT = "text/plain",
  HTML = "text/html",
  XML = "application/xml",
  PDF = "application/pdf",
  CSV = "text/csv",
  JAVASCRIPT = "application/javascript",
  OCTET_STREAM = "application/octet-stream",
  PNG = "image/png",
  JPEG = "image/jpeg",
  GIF = "image/gif",
  WEBP = "image/webp",
  SVG = "image/svg+xml",
}
